<a href="https://colab.research.google.com/github/arqPy/CAD/blob/main/Copy_of_A_Nodal_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise Nodal


LKT

$AI = 0$



In [3]:
def nos_ramos(circuito):

  nR = len(circuito)
  listNodes= set([])
  for ramo in circuito:
    no1 = ramo['NP']
    no2 = ramo['NC']

    listNodes.add(no1)
    listNodes.add(no2)
  nN = len(listNodes)
  return (nN - 1, nR)



In [4]:
# PROGRAMA PRINCIPAL --- Lê o grafo em um dicionário python
import numpy as np
def executaCircuito(circuito):
  (nN, nR) = nos_ramos(circuito)
  A = np.zeros((nN, nR))

  G = np.zeros((nR, nR))
  Is = np.zeros((nR, 1))
  Vs = np.zeros((nR, 1))

  for ramo in circuito:
    no1 = ramo['NP']
    no2 = ramo['NC']

    i = ramo['id']
    print(no1, no2, i)
    G[i - 1, i - 1] = 1./ramo['R']
    Vs[i - 1, 0] = ramo['Vs']
    Is[i - 1, 0] = ramo['Is']

    if (no1 != 0):
      A[no1-1, i-1 ] = 1.
    if (no2 != 0):
      A[no2-1, i-1 ] = -1.

  # Matrizes
  A = np.matrix(A, dtype=np.float64)
  G = np.matrix(G, dtype=np.float64)
  Vs = np.matrix(Vs, dtype=np.float64)
  Is = np.matrix(Is, dtype=np.float64)

  print(100*"*")
  print("Entrada ")
  print("\nA \n", A)
  print("\nG \n", G)
  print("\nVs \n", Vs)
  print("\nIs \n", Is)

  Gb = A*G*A.T
  In = A*(G*Vs - Is)
  E = (Gb.I)*In
  V = A.T*E
  I = Is + G*(V - Vs)

  print(100*"*")
  print("\nSaída ")
  print("\nCondutâncias de barras \n", Gb)
  print("\nCorrente Independente Resultante no Nó \n", In)
  print("\nTensão de Nó \n", E)
  print("\nTensão de ramo \n", V)
  print("\nCorrente de ramo \n", I)
  return

1 - *Exemplo*

![](https://github.com/arqPy/CAD/blob/main/Circuito_eletrico/fig/Circuito-Grafo-01.png?raw=true)

In [ ]:
# grafo do circuito TOPOLOGIA - LISTA DE RAMOS
circuito = [
    {'id': 1, 'NP': 0, 'NC': 1, 'R': 7, 'Vs': 0, 'Is': 16},
    {'id': 2, 'NP': 1, 'NC': 2, 'R': 1e-7, 'Vs': -2, 'Is': 0},
    {'id': 3, 'NP': 2, 'NC': 3, 'R': 2, 'Vs': 0, 'Is': 0},
    {'id': 4, 'NP': 2, 'NC': 0, 'R': 6, 'Vs': 0, 'Is': 0},
    {'id': 5, 'NP': 3, 'NC': 0, 'R': 4, 'Vs': 8, 'Is': 0},
    {'id': 6, 'NP': 0, 'NC': 3, 'R': 2, 'Vs': -6, 'Is': 0},
]
nos_ramos(circuito)

(3, 6)

In [ ]:
executaCircuito(circuito)

0 1 1
1 2 2
2 3 3
2 0 4
3 0 5
0 3 6
****************************************************************************************************
Entrada 

A 
 [[-1.  1.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.  0.]
 [ 0.  0. -1.  0.  1. -1.]]

G 
 [[1.42857143e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+07 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.00000000e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.66666667e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.50000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 5.00000000e-01]]

Vs 
 [[ 0.]
 [-2.]
 [ 0.]
 [ 0.]
 [ 8.]
 [-6.]]

Is 
 [[16.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
*********************************************************************************************

ENTRE COM O GRAFO REFERENTE AO CIRCUITO ABAIXO

![](https://github.com/arqPy/CAD/blob/main/Circuito_eletrico/fig/CIRCUITO_REDUZIDO.jpeg?raw=true)





In [ ]:
# Reduzindo
circuito = [
    {'id': 1, 'NP': 0, 'NC': 1, 'R': 7, 'Vs': 0, 'Is': 16},
    {'id': 2, 'NP': 1, 'NC': 2, 'R': 1e-7, 'Vs': -2, 'Is': 0},
    {'id': 3, 'NP': 2, 'NC': 0, 'R': 6, 'Vs': 0, 'Is': 0},
    {'id': 4, 'NP': 0, 'NC': 2, 'R': 10/3, 'Vs': -20/3, 'Is': 0}
]
executaCircuito(circuito)

0 1 1
1 2 2
2 0 3
0 2 4
****************************************************************************************************
Entrada 

A 
 [[-1.  1.  0.  0.]
 [ 0. -1.  1. -1.]]

G 
 [[1.42857143e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+07 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.66666667e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.00000000e-01]]

Vs 
 [[ 0.        ]
 [-2.        ]
 [ 0.        ]
 [-6.66666667]]

Is 
 [[16.]
 [ 0.]
 [ 0.]
 [ 0.]]
****************************************************************************************************

Saída 

Condutâncias de barras 
 [[ 10000000.14285714 -10000000.        ]
 [-10000000.          10000000.46666667]]

Corrente Independente Resultante no Nó 
 [[-19999984.]
 [ 20000002.]]

Tensão de Nó 
 [[28.00000087]
 [29.99999967]]

Tensão de ramo 
 [[-28.00000087]
 [ -1.9999988 ]
 [ 29.99999967]
 [-29.99999967]]

Corrente de ramo 
 [[11.99999988]
 [12.038

Circuito comparado com O LTSpice
![](https://github.com/arqPy/CAD/blob/main/Circuito_eletrico/fig/analiseNodal.png?raw=true)

In [59]:
circuito = [
    {'id': 1, 'NP': 3, 'NC': 1, 'R': 10/7, 'Vs': 0, 'Is': 1},
    {'id': 2, 'NP': 1, 'NC': 2, 'R': 5, 'Vs': 0, 'Is': -2},
    {'id': 3, 'NP': 2, 'NC': 3, 'R': 10, 'Vs': 0, 'Is': 0},
    {'id': 4, 'NP': 0, 'NC': 2, 'R': 4, 'Vs': 0, 'Is': 3},
    {'id': 5, 'NP': 0, 'NC': 3, 'R': 2, 'Vs': 0, 'Is': 0}
]
#executaCircuito(circuito)

V(n001): 7.15789 voltage
V(n003): 3.47368 voltage
V(n002): 5.05263 voltage
I(I3): 3 device_current
I(I2): 2 device_current
I(I1): 1 device_current
I(R6): -1.73684 device_current
I(R5): -0.421053 device_current
I(R4): 1.26316 device_current
I(R3): 0.157895 device_current
I(R2): 1.84211 device_current
I(R1): 0.736842 device_current
    
CORRETO


![](https://github.com/arqPy/CAD/blob/main/Circuito_eletrico/fig/fig-2.jpeg?raw=true)

In [ ]:
# lista de ramos do circuito TOPOLOGIA
circuito = [
    {'id': 1, 'NP': 1, 'NC': 0, 'R': 1e7, 'Vs': 0, 'Is': 8},
    {'id': 2, 'NP': 0, 'NC': 2, 'R': 8, 'Vs': 0, 'Is': 0},
    {'id': 3, 'NP': 2, 'NC': 1, 'R': 12, 'Vs': 0, 'Is': 0},
    {'id': 4, 'NP': 2, 'NC': 3, 'R': 4, 'Vs': 0, 'Is': 0},
    {'id': 5, 'NP': 3, 'NC': 1, 'R': 4, 'Vs': 0, 'Is': 0},
    {'id': 6, 'NP': 2, 'NC': 3, 'R': 1e-7, 'Vs': 0, 'Is': 0},
]


In [67]:
import numpy as np
class ramo:
  def __init__(self, Id, NP, NC, R, Vs=0, Is=0, V = 0, I = 0):
    self.Id = Id
    self.NP = NP
    self.NC = NC
    self.R = R
    self.Vs = Vs
    self.Is = Is
    self.V = V
    self.I = I

  def Vramo(self, V):
    self.V = V

  def Iramo(self, I):
    self.I = I

class NoCircuito:

  def __init__(self, Id, lstIn=[], lstOut=[], ddp = 0):
    self.Id = Id
    self.lstIn = lstIn
    self.lstOut = lstOut
    self.ddp = ddp

  def addRamoIn(self, ramo):
    self.lstIn.append(ramo)

  def Tensao(self, E):
    self.ddp = E

  def addRamoOut(self, ramo):
    self.lstOut.append(ramo)

class graphCircuit:
  def __init__(self, lstRamos=[], lstNos=[]):
    self.lstRamos = lstRamos
    self.lstNos = lstNos
    self.A = np.zeros((1, 1))
    self.G = np.zeros((1, 1))
    self.Is = np.zeros((1, 1))
    self.Vs = np.zeros((1, 1))

    self.Gb = np.zeros((1, 1))
    self.In = np.zeros((1, 1))
    self.E = np.zeros((1, 1))
    self.V = np.zeros((1, 1))
    self.I = np.zeros((1, 1))

  def addRamo(self, ramo):
    self.lstRamos.append(ramo)

  def addNo(self, nodo):
    self.lstNos.append(nodo)

  def listNos(self):
    return self.lstNos

  def setlistNos(self, lstNos):
    self.lstNos = lstNos

  def listRamos(self):
    return self.lstRamos

  def matrizes(self):
    nN = len(self.lstNos) - 1
    nR = len(self.lstRamos)
    self.A = np.zeros((nN, nR))

    self.G = np.zeros((nR, nR))
    self.Is = np.zeros((nR, 1))
    self.Vs = np.zeros((nR, 1))

    for ramo in self.lstRamos:
      no1 = ramo.NP
      no2 = ramo.NC

      i = ramo.Id

      self.G[i - 1, i - 1] = 1./ramo.R
      self.Vs[i - 1, 0] = ramo.Vs
      self.Is[i - 1, 0] = ramo.Is

      if (no1 != 0):
        self.A[no1-1, i-1 ] = 1.
      if (no2 != 0):
        self.A[no2-1, i-1 ] = -1.

  def imprimeMatrizes(self):
    print(100*"*")
    print("Entrada ")
    print("\nA \n", self.A)
    print("\nG \n", self.G)
    print("\nVs \n", self.Vs)
    print("\nIs \n", self.Is)

    print(100*"*")
    print("\nSaída ")
    print("\nCondutâncias de barras \n", self.Gb)
    print("\nCorrente Independente Resultante no Nó \n", self.In)
    print("\nTensão de Nó \n", self.E)
    print("\nTensão de ramo \n", self.V)
    print("\nCorrente de ramo \n", self.I)

  def run(self):
    # Matrizes
    self.A = np.matrix(self.A, dtype=np.float64)
    self.G = np.matrix(self.G, dtype=np.float64)
    self.Vs = np.matrix(self.Vs, dtype=np.float64)
    self.Is = np.matrix(self.Is, dtype=np.float64)

    self.Gb = self.A*self.G*self.A.T
    self.In = self.A*(self.G*self.Vs - self.Is)
    self.E = (self.Gb.I)*self.In
    self.V = self.A.T*self.E
    self.I = self.Is + self.G*(self.V - self.Vs)

  def updateGraph(self):
    for ramo in self.lstRamos:
      i = ramo.Id
      Iramo = self.I[i-1, 0]
      Vramo = self.V[i-1, 0]
      print('ramo:', i, 'I = ',Iramo, 'V = ',Vramo)
      ramo.Iramo = Iramo
      ramo.Vramo = Vramo



In [68]:
G = graphCircuit()
listNodes= set([])

for r in circuito:
  no1 = r['NP']
  no2 = r['NC']
  edge = ramo(r['id'],no1, no2, r['R'], r['Vs'], r['Is'])
  G.addRamo(edge)

  listNodes.add(no1)
  listNodes.add(no2)
G.setlistNos(listNodes)


In [69]:
G.listRamos()[3].Is

3

In [70]:
G.listNos()

{0, 1, 2, 3}

In [71]:
G.matrizes()

In [72]:
G.imprimeMatrizes()

****************************************************************************************************
Entrada 

A 
 [[-1.  1.  0.  0.  0.]
 [ 0. -1.  1. -1.  0.]
 [ 1.  0. -1.  0. -1.]]

G 
 [[0.7  0.   0.   0.   0.  ]
 [0.   0.2  0.   0.   0.  ]
 [0.   0.   0.1  0.   0.  ]
 [0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.5 ]]

Vs 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Is 
 [[ 1.]
 [-2.]
 [ 0.]
 [ 3.]
 [ 0.]]
****************************************************************************************************

Saída 

Condutâncias de barras 
 [[0.]]

Corrente Independente Resultante no Nó 
 [[0.]]

Tensão de Nó 
 [[0.]]

Tensão de ramo 
 [[0.]]

Corrente de ramo 
 [[0.]]


In [73]:
G.run()

In [74]:
G.updateGraph()

ramo: 1 I =  -1.5789473684210518 V =  -3.6842105263157885
ramo: 2 I =  -1.5789473684210529 V =  2.1052631578947354
ramo: 3 I =  0.1578947368421053 V =  1.578947368421053
ramo: 4 I =  1.7368421052631575 V =  -5.05263157894737
ramo: 5 I =  -1.7368421052631584 V =  -3.473684210526317


In [75]:
for r in G.listRamos():
  print('Ramo:', r.Id, 'R = ', r.R, 'Vs = ', r.Vs, 'Is = ', r.Is, 'I = ', r.I, 'V = ', r.V)

Ramo: 1 R =  1.4285714285714286 Vs =  0 Is =  1 I =  0 V =  0
Ramo: 2 R =  5 Vs =  0 Is =  -2 I =  0 V =  0
Ramo: 3 R =  10 Vs =  0 Is =  0 I =  0 V =  0
Ramo: 4 R =  4 Vs =  0 Is =  3 I =  0 V =  0
Ramo: 5 R =  2 Vs =  0 Is =  0 I =  0 V =  0
